apiVersion: v2
name: pi-homepage
description: A Helm chart for the Next.js homepage.
type: application
version: 0.1.0
appVersion: "1.0.0"
icon: https://raw.githubusercontent.com/ethn1ee/pi/main/icon.svg

dependencies:
  - name: common
    version: "0.1.0"
    repository: "file://../_common"
