replicaCount: 1

image:
  repository: ghcr.io/ethn1ee/spitikos/homepage
  pullPolicy: Always
  tag: 48fa2c4ae3e51b554e9a29c4654515f1d1cf9acf

service:
  type: ClusterIP
  port: 80
  containerPort: 3000
  portName: http

ingress:
  enabled: true
  host: pi.taehoonlee.dev
  path: /
