replicaCount: 1

image:
  repository: ghcr.io/ethn1ee/pi-homepage
  pullPolicy: Always
  tag: a5a3eaa70aa4692d491fbc9af2a539ccec7ae2b2

service:
  type: ClusterIP
  port: 80
  containerPort: 3000
  portName: http

ingress:
  enabled: true
  host: pi.taehoonlee.dev
  path: /
