replicaCount: 1

image:
  repository: ghcr.io/ethn1ee/spitikos/homepage
  pullPolicy: Always
  tag: 6b4693343ce659eda7acb7562f7dee037ee4778d

service:
  type: ClusterIP
  port: 80
  containerPort: 3000
  portName: http

ingress:
  enabled: true
  host: pi.taehoonlee.dev
  path: /
