replicaCount: 1

image:
  repository: ghcr.io/ethn1ee/pi-homepage
  pullPolicy: Always
  tag: 67212d08877d94b6a2ab792dac0bbe6ae0e8538a

service:
  type: ClusterIP
  port: 80
  containerPort: 3000
  portName: http

ingress:
  enabled: true
  host: pi.taehoonlee.dev
  path: /
