replicaCount: 1

image:
  repository: ghcr.io/ethn1ee/pi-homepage
  pullPolicy: Always
  tag: latest

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  host: pi.taehoonlee.dev
  path: /
