replicaCount: 1

image:
  repository: ghcr.io/ethn1ee/pi-homepage
  pullPolicy: Always
  tag: 693dc3a6a0824c70e34c87f0be083fff72ca3653

service:
  type: ClusterIP
  port: 80
  containerPort: 3000
  portName: http

ingress:
  enabled: true
  host: pi.taehoonlee.dev
  path: /
