apiVersion: v2
icon: https://raw.githubusercontent.com/ethn1ee/pi/main/icon.svg
name: misc-whoami
description: A Helm chart for deploying the whoami application.
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: common
    version: "0.1.0"
    repository: "file://../_common"
