replicaCount: 1

image:
  repository: traefik/whoami
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  host: pi.taehoonlee.dev
  path: /whoami
