apiVersion: v2
icon: https://raw.githubusercontent.com/ethn1ee/pi/main/icon.svg
name: stats
description: A Helm chart for the Raspberry Pi Stats SSE server
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: common
    version: "0.1.0"
    repository: "file://../../common"