replicaCount: 1

image:
  repository: ghcr.io/ethn1ee/pi-api-stats
  pullPolicy: Always
  tag: aa4bb58753a47db2ad9939e3eb10790692d58c7b

service:
  type: ClusterIP
  port: 50051
  containerPort: 50051
  portName: grpc

ingress:
  enabled: false
