replicaCount: 1

image:
  repository: ghcr.io/ethn1ee/pi-api-stats
  pullPolicy: Always
  tag: 830ea1657cfe32a43e588ce06c19220ab34958d4

service:
  type: ClusterIP
  port: 50051
  containerPort: 50051
  portName: grpc

ingress:
  enabled: false
