replicaCount: 1

image:
  repository: ghcr.io/ethn1ee/pi-api-stats
  pullPolicy: Always
  tag: bccd37e4f5abccc51f53556629bf85f3c5ae2fda

service:
  type: ClusterIP
  port: 50051
  containerPort: 50051
  portName: grpc

ingress:
  enabled: false
