replicaCount: 1

image:
  repository: ghcr.io/ethn1ee/pi-api-stats
  pullPolicy: Always
  tag: 72947fa776f87866e96142e13b1b55d210bf43f1

service:
  type: ClusterIP
  port: 50051
  containerPort: 50051
  portName: grpc

ingress:
  enabled: false
