replicaCount: 1

image:
  repository: ghcr.io/ethn1ee/pi-api-stats
  pullPolicy: Always
  tag: 3443bc0bf75aee6d8235eea9f0162c91248d0a1a

service:
  type: ClusterIP
  port: 50051
  containerPort: 50051
  portName: grpc

ingress:
  enabled: false
