prometheus:
  alertmanager:
    enabled: false

  # -- Disable Pushgateway as we are using a pull-based model.
  pushgateway:
    enabled: false

  grafana:
    enabled: false

  server:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

    # -- Use an emptyDir for storage. This is non-persistent and will be lost
    # on pod restarts, but avoids the complexity of setting up persistent storage.
    persistentVolume:
      enabled: false
    emptyDir:
      enabled: true

    ingress:
      enabled: false

    # -- ServiceMonitor selector configuration
    serviceMonitorSelector: {} # An empty selector matches all labels.

    # -- PodMonitor selector configuration.
    podMonitorSelector: {} # Match all PodMonitors as well.
