# passed to the official 'traefik' subchart.
traefik:
  dashboard:
    enabled: true
  api:
    insecure: true
  service:
    type: NodePort
    nodePorts:
      web: 30080
  entryPoints:
    websecure:
      address: ""

# Values for our custom templates in this chart
ingress:
  enabled: true
  host: traefik-pi.taehoonlee.dev
