dashboard:
  enabled: true

api:
  insecure: true

service:
  type: NodePort

ports:
  web:
    nodePort: 30080

# Disable the 'websecure' (HTTPS) entrypoint as TLS is handled by Cloudflare
entryPoints:
  websecure:
    address: ""
