replicaCount: 1

image:
  repository: ghcr.io/ethn1ee/pi-stats
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  host: pi.taehoonlee.dev
  path: /api/stats
