apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server-ingress
  namespace: argocd
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`argocd-pi.taehoonlee.dev`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
