apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-prometheus-proxy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/spitikos/charts.git
    targetRevision: HEAD
    path: charts/api/prometheus-proxy
    helm:
      releaseName: prometheus-proxy
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
