apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pi-api-whoami
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/ethn1ee/pi-api-whoami.git'
    targetRevision: HEAD
    path: charts/api/whoami
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pi-api-whoami
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
