name: Release

on:
  workflow_call:
    inputs:
      chart_path:
        required: true
        type: string
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
    secrets:
      gha_pat:
        required: true

jobs:
  docker-publish:
    name: Build and Push Docker Image
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/arm64
          tags: ghcr.io/spitikos/${{ inputs.image_name }}:${{ inputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-chart:
    name: Update Image Tag in Chart
    runs-on: ubuntu-latest
    needs: docker-publish
    permissions:
      contents: write
    strategy:
      matrix:
        chart_path: ${{ fromJSON(inputs.chart_path) }}

    steps:
      - name: Checkout Charts Repository
        uses: actions/checkout@v4
        with:
          repository: spitikos/charts
          token: ${{ secrets.gha_pat }}
          path: charts

      - name: Sanitize chart path for artifact name
        id: sanitize
        run: |
          sanitized_name=$(echo "${{ matrix.chart_path }}" | tr '/' '-')
          echo "name=${sanitized_name}" >> $GITHUB_OUTPUT

      - name: Update image tag in ${{ matrix.chart_path }}
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag = "${{ inputs.image_tag }}"' "./charts/${{ matrix.chart_path }}/values.yaml"

      - name: Commit changes to ${{ matrix.chart_path }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          git add .

          if ! git diff --staged --quiet; then
            git commit -m "Update ${{ inputs.image_name }} image to tag ${{ inputs.image_tag }}"
            git push origin main
          else
            echo "No changes to commit."
          fi
