name: Release

on:
  workflow_call:
    inputs:
      chart_path:
        required: true
        type: string
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
    secrets:
      gha_pat:
        required: true

jobs:
  docker-publish:
    name: Build and Push Docker Image
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-chart:
    name: Update Chart
    runs-on: ubuntu-latest
    needs: docker-publish
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/spitikos
          token: ${{ secrets.GHA_PAT }}

      - name: Update image tag
        run: |
          sed -i "s/tag: .*/tag: ${{ inputs.image_tag }}/" ${{ inputs.chart_path }}/values.yaml

      - name: Commit Changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add ${{ inputs.chart_path }}/values.yaml
          git commit -m "update ${{ inputs.image_name }} image"
          git push origin main
