name: Release

on:
  workflow_call:
    inputs:
      deployment:
        required: true
        type: string
      namespace:
        required: true
        type: string
      image_name:
        required: true
        type: string

jobs:
  docker-publish:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:${{ github.sha }}

  update-image:
    name: Update deployment image
    runs-on: ubuntu-latest

    steps:
      - name: Set image with git sha
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: set image deployment/${{ inputs.deployment }} ${{ inputs.image_name }}=ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:${{ github.sha }}
