name: Release

on:
  workflow_call:
    inputs:
      chart_path:
        required: true
        type: string
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
    secrets:
      gha_pat:
        required: true

jobs:
  docker-publish:
    name: Build and Push Docker Image
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  update-chart:
    name: Update Chart
    runs-on: ubuntu-latest
    needs: docker-publish
    permissions:
      contents: write
    strategy:
      matrix:
        chart_path: ${{ fromJSON(inputs.chart_path) }}

    steps:
      - name: Checkout Charts Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/charts
          token: ${{ secrets.GHA_PAT }}
          path: charts

      - name: Setup yq
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install yq

      - name: Update image tag in ${{ matrix.chart_path }}
        run: |
          ls
          yq e '.image.tag = "${{ inputs.image_tag }}"' -i "${{ matrix.chart_path }}/values.yaml"

  commit-changes:
    name: Commit All Chart Changes
    runs-on: ubuntu-latest
    needs: update-chart
    permissions:
      contents: write

    steps:
      - name: Checkout Charts Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/charts
          token: ${{ secrets.GH_PAT }}

      - name: Commit Changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          # Check if there are any changes to commit
          if ! git diff --quiet; then
            git commit -am "Update ${{ inputs.image_name }} image to tag ${{ inputs.image_tag }}"
            git push origin main
          else
            echo "No changes to commit."
          fi
